[build]
  # Replace environment variables in HTML files
  command = "./build.sh"
  publish = "."

[build.environment]
  # Environment settings
  NODE_VERSION = "18"

[[edge_functions]]
  path = "/*"
  function = "geo-cookie"

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy for enhanced security
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://unpkg.com; script-src-elem 'self' 'unsafe-inline' https://www.googletagmanager.com https://unpkg.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://tile.openstreetmap.org; connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://region1.analytics.google.com https://region1.google-analytics.com https://stats.g.doubleclick.net https://www.googletagmanager.com https://tile.openstreetmap.org https://unpkg.com"

[[headers]]
  # Cache static assets for 1 year
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Cache favicon files for 1 week
  for = "/favicon_io/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  # Set proper MIME type for web manifest
  for = "/favicon_io/site.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  # Set proper MIME type for SVG files
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[redirects]]
  # Redirect any 404s to index page for SPA-like behavior if needed
  from = "/*"
  to = "/index.html"
  status = 200
  # Only apply to paths that don't exist as files
  conditions = {Role = ["admin"], Country = ["US"]}
  force = false

# Custom 404 page (optional)
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 404